version: "3"

services:
  python_server:
    build:
      context: python_server
    env_file: .env
    environment:
      - "MY_NAME:${MY_NAME}" # キーとバリューは同じじゃないと行けないみたい。

  rust_server:
    build:
      context: rust_server
    env_file: .env
    environment:
      - "MY_NAME:${MY_NAME}" # 例えば、 "WHY_NAME:${MY_NAME}" とかだとエラーになる。　
